ConfigVersion = 5

[General]
CheckForUpdates = false
IncludeNightlyBuilds = false
PauseWhenUnfocused = false
RememberLastLoadedDisc = false

[General.PathOverrides]
IPLROMImages = "/storage/roms/bios"
ROMCartImages = "/storage/roms/bios"
CDBlockROMImages = "/storage/roms/bios/ymir/cdb"
BackupMemory = "/storage/roms/saturn/ymir/backup"
ExportedBackups = "/storage/roms/saturn/ymir/backup/exported"
SaveStates = "/storage/roms/savestates/saturn/ymir"
Screenshots = "/storage/roms/screenshots"

[System]
AutoDetectRegion = true
InternalBackupRAMImagePath = "/storage/roms/saturn/ymir/bup-int.bin"
InternalBackupRAMPerGame = false

[Input.Port1]
PeripheralType = "ControlPad"

[Input.Port2]
PeripheralType = "ControlPad"

[Video]
AutoResizeWindow = false
DisplayVideoOutputInWindow = false
FullScreen = true
ForceAspectRatio = true
ForcedAspect = 1.3333333333333333
ForceIntegerScaling = false

[Video.Enhancements]
Deinterlace = false
TransparentMeshes = false
