# HiFi use case for the TrimUI TG4070

SectionVerb {
	EnableSequence [
		cset "name='QUINARY_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='QUINARY_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	ConflictingDevice [
		"Headphones"
	]

	Value {
		PlaybackPriority 150
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "Speaker"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"

	ConflictingDevice [
		"Speaker"
	]

	EnableSequence [
		cset "name='QUINARY_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='QUINARY_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	Include.wcdhpe.File "/codecs/wcd937x/HeadphoneEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd937x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "HP"
		JackControl "Headphone Jack"
		JackHWMute "Speaker"
	}
}

SectionDevice."Headset Mic" {
	Comment "Headset microphone"

	Include.wcdmice.File "/codecs/wcd937x/HeadphoneMicEnableSeq.conf"
	Include.wcdmicd.File "/codecs/wcd937x/HeadphoneMicDisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/HeadphoneMicEnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/HeadphoneMicDisableSeq.conf"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},2"
		CaptureMixerElem "ADC2"
		JackControl "Mic Jack"
	}
}
