# ROCKNIX: NetworkManager owns Ethernet and Wi-Fi; Wi-Fi uses iwd as backend.

[main]
auth-polkit=false
plugins=keyfile
dhcp=internal
dns=systemd-resolved

[device]
wifi.backend=iwd

[keyfile]
path=/storage/.config/NetworkManager/system-connections
# ROCKNIX USB gadget not DHCP to a router.
unmanaged-devices=interface-name:gadget;interface-name:usb0;interface-name:usbnet;interface-name:rndis0
