#!/bin/sh

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2025 ROCNIX (https://github.com/ROCKNIX)

# Set quantom audio hack

. /etc/profile

pw-metadata -n settings 0 clock.min-quantum 32
pw-metadata -n settings 0 clock.force-quantum 1023
pw-metadata -n settings 0 clock.force-quantum 1024
