#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)
# RK3566: CPU DVFS drives I2C to PMIC; rate-limit ondemand to 300 ms (schedutil uses DTS clock-latency).

ondemand() {
  set_cpu_gov ondemand
  set_dmc_gov ondemand
  local gov="/sys/devices/system/cpu/cpufreq/ondemand"
  if [ -d "$gov" ]; then
    echo 300000 > "$gov/sampling_rate" 2>/dev/null
    echo 80 > "$gov/up_threshold" 2>/dev/null
    echo 10 > "$gov/sampling_down_factor" 2>/dev/null
    echo 1 > "$gov/io_is_busy" 2>/dev/null
  fi
}
