# Suspend ALSA audio nodes after 5 seconds

monitor.alsa.rules = [
  {
    matches = [ { node.name = "~alsa_output.*" } ]
    actions = {
      update-props = {
        node.suspend-on-idle = true
        session.suspend-timeout-seconds = 5
      }
    }
  }
  {
    matches = [ { node.name = "~alsa_input.*" } ]
    actions = {
      update-props = {
        node.suspend-on-idle = true
        session.suspend-timeout-seconds = 5
      }
    }
  }
]
