SYSTEM_NAME="bbcmicro"
SYSTEM_FULLNAME="BBC Micro"
SYSTEM_MANUFACTURER="Acorn"
SYSTEM_RELEASE="1981"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/bbcmicro"
SYSTEM_EXTENSION=".ssd .dsd"
SYSTEM_PLATFORM="bbcmicro"
SYSTEM_THEME="bbcmicro"
SYSTEM_WIKI_PATH="bbcmicro"
