SYSTEM_NAME="bk"
SYSTEM_FULLNAME="BK"
SYSTEM_MANUFACTURER="Elektronika"
SYSTEM_RELEASE="1985"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/bk"
SYSTEM_EXTENSION=".bin .img .dsk .bkd .zip .7z"
SYSTEM_PLATFORM="bk"
SYSTEM_THEME="bk"
SYSTEM_WIKI_PATH="bk"
