SYSTEM_NAME="dice"
SYSTEM_FULLNAME="DICE"
SYSTEM_MANUFACTURER="Arcade"
SYSTEM_RELEASE="1972"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/dice"
SYSTEM_EXTENSION=".zip .dmy"
SYSTEM_PLATFORM="arcade"
SYSTEM_THEME="dice"
SYSTEM_WIKI_PATH="dice"
