SYSTEM_NAME="enterprise"
SYSTEM_FULLNAME="Enterprise 64/128"
SYSTEM_MANUFACTURER="Enterprise Computers"
SYSTEM_RELEASE="1985"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/enterprise"
SYSTEM_EXTENSION=".img .dsk .vhd .tap .dtf .com .trn .128 .bas .zip"
SYSTEM_PLATFORM="enterprise"
SYSTEM_THEME="enterprise"
SYSTEM_WIKI_PATH="enterprise"
