SYSTEM_NAME="gp32"
SYSTEM_FULLNAME="GP32"
SYSTEM_MANUFACTURER="GamePark"
SYSTEM_HARDWARE="portable"
SYSTEM_PATH="/storage/roms/gp32"
SYSTEM_EXTENSION=".smc .zip .7z"
SYSTEM_PLATFORM="gp32"
SYSTEM_THEME="gp32"
SYSTEM_WIKI_PATH="gp32"
