SYSTEM_NAME="heroic"
SYSTEM_FULLNAME="Heroic Games Launcher"
SYSTEM_MANUFACTURER="Heroic"
SYSTEM_RELEASE="System"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/heroic/"
SYSTEM_EXTENSION=".sh"
SYSTEM_PLATFORM="heroic"
SYSTEM_THEME="heroic"
SYSTEM_WIKI_PATH="heroic"
