SYSTEM_NAME="ios"
SYSTEM_FULLNAME="iOS"
SYSTEM_MANUFACTURER="Apple"
SYSTEM_RELEASE="2008"
SYSTEM_HARDWARE="portable"
SYSTEM_PATH="/storage/roms/ios"
SYSTEM_EXTENSION=".ipa .app"
SYSTEM_PLATFORM="ios"
SYSTEM_THEME="ios"
SYSTEM_WIKI_PATH="ios"
