SYSTEM_NAME="n64dd"
SYSTEM_FULLNAME="Nintendo 64 Disk Drive"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="1999"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/n64dd"
SYSTEM_EXTENSION=".z64 .n64 .v64 .ndd .zip .7z"
SYSTEM_PLATFORM="n64dd"
SYSTEM_THEME="n64dd"
SYSTEM_WIKI_PATH="n64dd"
