SYSTEM_NAME="ndsiware"
SYSTEM_FULLNAME="Nintendo DSiWare"
SYSTEM_PATH="/storage/roms/ndsiware"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="2008"
SYSTEM_HARDWARE="portable"
SYSTEM_EXTENSION=".nds .zip .7z"
SYSTEM_PLATFORM="nds"
SYSTEM_THEME="ndsiware"
SYSTEM_WIKI_PATH="nds"
