SYSTEM_NAME="ps4"
SYSTEM_FULLNAME="PlayStation 4"
SYSTEM_MANUFACTURER="Sony"
SYSTEM_RELEASE="2013"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/ps4"
SYSTEM_EXTENSION=".ps4 .zar"
SYSTEM_PLATFORM="ps4"
SYSTEM_THEME="ps4"
SYSTEM_WIKI_PATH="ps4"
