SYSTEM_NAME="steam"
SYSTEM_FULLNAME="Steam"
SYSTEM_MANUFACTURER="Valve"
SYSTEM_RELEASE="System"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/.local/share/applications"
SYSTEM_EXTENSION=".desktop"
SYSTEM_PLATFORM="pc"
SYSTEM_THEME="steam"
SYSTEM_WIKI_PATH="steam"
