SYSTEM_NAME="triforce"
SYSTEM_FULLNAME="Triforce"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="2002"
SYSTEM_HARDWARE="arcade"
SYSTEM_PATH="/storage/roms/triforce"
SYSTEM_EXTENSION=".gcm .iso .gcz .ciso .wbfs .rvz .dol .m3u"
SYSTEM_PLATFORM="triforce"
SYSTEM_THEME="triforce"
SYSTEM_WIKI_PATH="triforce"
