SYSTEM_NAME="tvc"
SYSTEM_FULLNAME="TV Computer"
SYSTEM_MANUFACTURER="Videoton"
SYSTEM_RELEASE="1986"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/tvc"
SYSTEM_EXTENSION=".cas .dsk .img .tvcwav .zip"
SYSTEM_PLATFORM="tvc"
SYSTEM_THEME="tvc"
SYSTEM_WIKI_PATH="tvc"
