SYSTEM_NAME="wiiware"
SYSTEM_FULLNAME="WiiWare"
SYSTEM_MANUFACTURER="Nintendo"
SYSTEM_RELEASE="2008"
SYSTEM_HARDWARE="console"
SYSTEM_PATH="/storage/roms/wiiware"
SYSTEM_EXTENSION=".gcm .iso .gcz .ciso .wbfs .rvz .dol .wad .m3u"
SYSTEM_PLATFORM="wii"
SYSTEM_THEME="wiiware"
SYSTEM_WIKI_PATH="wii"
