#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2026-present ROCKNIX (https://github.com/ROCKNIX)
#
# SM6115-specific minimal system-sleep handler.

BT_UART_WAKEUP=/sys/devices/platform/soc@0/4ac0000.geniqup/4a8c000.serial/power/wakeup

bt_uart_wakeup() {
  [ -e "${BT_UART_WAKEUP}" ] && echo "${1}" > "${BT_UART_WAKEUP}"
}

case $1 in
  pre)
    rocknix-games-freeze freeze
    bt_uart_wakeup disabled
    ;;
  post)
    bt_uart_wakeup enabled
    rocknix-games-freeze thaw
    ;;
esac

exit 0
