monitor.alsa.rules = [
  {
    matches = [
      {
        media.class = "Audio/Sink"
        api.alsa.path = "hw:RetroidPocket,3"
      }
    ]
    actions = {
      update-props = {
        audio.format = "S16LE"
        audio.rate = 48000
        audio.channels = 2
        audio.position = [ "FL" "FR" ]
        api.alsa.disable-mmap = true
        api.alsa.period-size = 480
        api.alsa.period-num = 8
      }
    }
  }
]
