blank_issues_enabled: false
contact_links:
  - name: Help and Support
    url: https://discord.gg/seTxckZjJy
    about: Please ask for help and post questions in our Discord
  - name: Feature Requests
    url: https://discord.gg/seTxckZjJy
    about: Please ask for feature requests in our Discord
