# use built-in dhcp client
[General]
EnableNetworkConfiguration=true
ControlPortOverNL80211=false

[Network]
RoutePriorityOffset=200

NameResolvingService=systemd
EnableIPv6=true


[Scan]
MaximumPeriodicScanInterval=30
