---
initial-setup: true
gdbstub: false
log-active-shaders: false
log-uniforms: false
log-compat-warn: false
validation-layer: true
pstv-mode: false
show-mode: false
demo-mode: false
show-gui: false
show-info-bar: false
apps-list-grid: false
display-system-apps: false
stretch_the_display_area: false
fullscreen_hd_res_pixel_perfect: false
show-live-area-screen: false
icon-size: 64
archive-log: false
backend-renderer: Vulkan
custom-driver-name: ""
turbo-mode: false
gpu-idx: 0
high-accuracy: false
resolution-multiplier: 1
disable-surface-sync: true
screen-filter: Bilinear
v-sync: true
anisotropic-filtering: 1
texture-cache: true
async-pipeline-compilation: true
show-compile-shaders: false
hashless-texture-cache: false
import-textures: false
export-textures: false
export-as-png: true
memory-mapping: double-buffer
boot-apps-full-screen: true
audio-backend: SDL
audio-volume: 100
ngs-enable: true
sys-button: 1
sys-lang: 1
sys-date-format: 2
sys-time-format: 0
cpu-pool-size: 10
modules-mode: 0
delay-background: 0
delay-start: 0
background-alpha: 0.3
log-level: 8
cpu-opt: true
pref-path: /storage/roms/psvita/vita3k/
discord-rich-presence: false
wait-for-debugger: false
color-surface-debug: false
show-touchpad-cursor: true
performance-overlay: false
performance-overlay-detail: 0
performance-overlay-position: 0
enable-gamepad-overlay: false
overlay-show-touch-switch: false
overlay-scale: 1
overlay-opacity: 100
screenshot-format: 1
disable-motion: false
controller-analog-multiplier: 1
keyboard-button-select: 229
keyboard-button-start: 40
keyboard-button-up: 82
keyboard-button-right: 79
keyboard-button-down: 81
keyboard-button-left: 80
keyboard-button-l1: 20
keyboard-button-r1: 8
keyboard-button-l2: 24
keyboard-button-r2: 18
keyboard-button-l3: 9
keyboard-button-r3: 11
keyboard-button-triangle: 25
keyboard-button-circle: 6
keyboard-button-cross: 27
keyboard-button-square: 29
keyboard-leftstick-left: 4
keyboard-leftstick-right: 7
keyboard-leftstick-up: 26
keyboard-leftstick-down: 22
keyboard-rightstick-left: 13
keyboard-rightstick-right: 15
keyboard-rightstick-up: 12
keyboard-rightstick-down: 14
keyboard-button-psbutton: 19
keyboard-gui-toggle-gui: 10
keyboard-gui-fullscreen: 68
keyboard-gui-toggle-touch: 23
keyboard-toggle-texture-replacement: 0
keyboard-take-screenshot: 0
user-id: 00
user-auto-connect: true
user-lang: ""
display-info-message: false
show-welcome: false
check-for-updates: false
file-loading-delay: 0
asia-font-support: false
shader-cache: true
spirv-shader: false
fps-hack: false
current-ime-lang: 4
psn-signed-in: 0
http-enable: false
http-timeout-attempts: 50
http-timeout-sleep-ms: 100
http-read-end-attempts: 10
http-read-end-sleep-ms: 250
adhoc-addr: 0
tracy-primitive-impl: false
controller-binds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
controller-led-color:
  []
lle-modules:
  []
ime-langs:
  - 4
tracy-advanced-profiling-modules:
  []
...
