Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm6115/HiFi-MangmiAirX.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
	cset "name='SPK_L PCM Playback Volume' 72"
	cset "name='SPK_R PCM Playback Volume' 72"
	cset "name='SPK_L Profile Set' 0"
	cset "name='SPK_R Profile Set' 0"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
