[Service]
# Relax sandboxing to prevent race conditions on boot with OverlayFS
# Fixes error: NAMESPACE "Failed to set up mount namespacing" which can occur based on overlayfs setup speed
PrivateTmp=no
ProtectSystem=full
TimeoutStopSec=1s
