# ROCKNIX Networking Enhancements
net.ipv4.ip_forward = 1
net.ipv6.conf.all.accept_ra = 2
net.ipv6.conf.default.accept_ra = 2
net.ipv6.conf.all.forwarding = 1

# BBR & FQ_CODEL Tuning
net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = bbr
