# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024-present ROCKNIX (https://github.com/ROCKNIX)

. ${ROOT}/packages/addons/addon-depends/libzip/package.mk

PKG_DEPENDS_TARGET+=" gnutls openssl"
PKG_CMAKE_OPTS_TARGET="${PKG_CMAKE_OPTS_TARGET/-DENABLE_GNUTLS=OFF/-DENABLE_GNUTLS=ON}"
PKG_CMAKE_OPTS_TARGET="${PKG_CMAKE_OPTS_TARGET/-DENABLE_OPENSSL=OFF/-DENABLE_OPENSSL=ON}"
PKG_CMAKE_OPTS_TARGET="${PKG_CMAKE_OPTS_TARGET/-DBUILD_SHARED_LIBS=OFF/-DBUILD_SHARED_LIBS=ON}"

unset -f post_makeinstall_target
