# Use case configuration for MANGMI Air X.

SectionVerb {

	EnableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='Speaker Switch' on"
		cset "name='Headphone Jack Switch' off"
	]

	DisableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='Speaker Switch' off"
		cset "name='Headphone Jack Switch' off"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones Playback"

	EnableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='Headphone Jack Switch' on"
		cset "name='Speaker Switch' off"
	]

	DisableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='Headphone Jack Switch' off"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	EnableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='Speaker Switch' on"
		cset "name='Headphone Jack Switch' off"
	]

	DisableSequence [
		cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='Speaker Switch' off"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
	}
}
