Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm6115/HiFi-MangmiAirX.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='HPVol SPKVol Switch' 'HPVOL: HPL+HPR, SPKVOL: SPKL+SPKR'"
	cset "name='DAC Playback Volume' 80%"
	cset "name='HPL Playback Volume' 80%"
	cset "name='HPR Playback Volume' 80%"
	cset "name='SPKL Playback Volume' 80%"
	cset "name='SPKR Playback Volume' 80%"
	cset "name='L Profile Set' 'Music'"
	cset "name='R Profile Set' 'Music'"
	cset "name='L PCM Playback Volume' 80%"
	cset "name='R PCM Playback Volume' 80%"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
