Syntax 4

SectionUseCase."HiFi" {
	File "/Qualcomm/sm6115/HiFi-MangmiAirX.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='SEC_MI2S_RX Audio Mixer MultiMedia1' 1"
	cset "name='HPVol SPKVol Switch' 3"
	cset "name='DAC Playback Volume' 191"
	cset "name='HPL Playback Volume' 191"
	cset "name='HPR Playback Volume' 191"
	cset "name='SPKL Playback Volume' 191"
	cset "name='SPKR Playback Volume' 191"
	cset "name='ADC Capture Volume' 191"
	cset "name='ADC PGA Gain Volume' 4"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
