# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)

SWAPFILE="$HOME/.cache/swapfile"
ZRAM_SIZE="@ZRAM_SWAP_SIZE@"
SWAP_ENABLED="@SWAP_ENABLED_DEFAULT@"
SWAP_FILE_SIZE="@SWAP_FILE_SIZE@"
ZRAM_ALGO="@ZRAM_COMPRESSION_ALGO@"
