#!/bin/sh
# Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
# Copyright (C) 2016-present Team LibreELEC (https://libreelec.tv)

SWAPFILE="$HOME/.cache/swapfile"
ZRAM_SIZE="@ZRAM_SWAP_SIZE@"
SWAP_ENABLED="@SWAP_ENABLED_DEFAULT@"
SWAP_FILE_SIZE="@SWAP_FILE_SIZE@"
SWAP_PRIORITY="@SWAP_PRIORITY@"
ZRAM_ALGO="@ZRAM_COMPRESSION_ALGO@"
KSM_ENABLE="@KSM_ENABLE@"
