vm.dirty_writeback_centisecs=1500
-kernel.nmi_watchdog=0
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
net.ipv6.conf.all.accept_ra=2
net.ipv6.conf.default.accept_ra=2
-net.ipv4.tcp_congestion_control=bbr
