vm.dirty_writeback_centisecs=1500
-kernel.nmi_watchdog=0
net.ipv6.conf.all.accept_ra=2
net.ipv6.conf.default.accept_ra=2
-net.ipv4.tcp_congestion_control=bbr
vm.max_map_count=2147483642
fs.inotify.max_user_instances=1024
fs.inotify.max_user_watches=524288
kernel.panic=20
