name: Build self-hosted

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types: [ assigned ]

jobs:
  require-approval:
    runs-on: ubuntu-24.04
    environment:
      name: ${{ github.event_name == 'pull_request' && 'pr-approval' || 'auto' }}
    steps:
      - run: echo "PR approved"
  build-devices:
    name: Build Devices
    needs: require-approval
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: RK3326
          - device: RK3399
          - device: RK3566
          - device: RK3588
          - device: S922X
          - device: H700
          - device: SDM845
          - device: SM8250
          - device: SM8550
          - device: SM8650
    uses: ./.github/workflows/build-self-hosted-device.yml
    secrets: inherit
    with:
      DEVICE: ${{ matrix.device }}