name: Build eden-sa

on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      DEVICE:
        required: true
        type: string
      OWNER_LC:
        required: true
        type: string
      CODEX_SUPPORT:
        required: true
        type: string

jobs:
  build-aarch64-eden-sa:
    # ← SM8250, SM8550, SM8650에서만 실행
    if: ${{ inputs.DEVICE == 'SM8250' || inputs.DEVICE == 'SM8550' || inputs.DEVICE == 'SM8650' || inputs.DEVICE == 'SM8750' }}
    runs-on: ubuntu-24.04
    env:
      EMULATION_DEVICE: no
      ENABLE_32BIT: no
      TARGET_TYPE: emus_only
      JAVA_HOME: /usr
      PROJECT: ${{ inputs.PROJECT }}
      DEVICE: ${{ inputs.DEVICE }}
      CODEX_SUPPORT: ${{ inputs.CODEX_SUPPORT }}
      ARCH: aarch64
      CACHE_KEY: ccache-aarch64-${{ inputs.DEVICE }}-eden-sa-${{ github.sha }}
      DISABLE_COLORS: yes
      CCACHE_COMPILERCHECK: content
      CCACHE_COMPRESS: 1
      CCACHE_COMPRESSLEVEL: 6
      CCACHE_SLOPPINESS: pch_defines,time_macros,include_file_mtime,include_file_ctime

    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 6144
          swap-size-mb: 8192
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Retrieve ccache
        run: |
          URL="https://github.com/${{ github.repository_owner }}/${{ vars.CACHE_REPO || 'distribution-cache' }}/releases/download/ccache/ccache-aarch64-${{ inputs.DEVICE }}-eden-sa.tar"
          curl -L --fail --silent --show-error "$URL" | tar -xvf - || echo "Cache archive not found, skipping."

      - name: Download aarch64-toolchain (${{ inputs.DEVICE }})
        uses: actions/download-artifact@v8
        with:
          name: aarch64-toolchain (${{ inputs.DEVICE }})

      - name: Extract artifact aarch64-toolchain
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            tar --zstd -xf build.aarch64-toolchain.tar.zst
          max_attempts: 3
          retry_interval: 10

      - name: Clean up compressed aarch64-toolchain file
        run: rm build.aarch64-toolchain.tar.zst

      - name: Download aarch64 (${{ inputs.DEVICE }})
        uses: actions/download-artifact@v8
        with:
          name: aarch64 (${{ inputs.DEVICE }})

      - name: Extract artifact aarch64
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            tar -xf build.aarch64.tar
          max_attempts: 3
          retry_interval: 10

      - name: Clean up compressed aarch64 file
        run: rm build.aarch64.tar

      - name: Download build aarch64 (${{ inputs.DEVICE }})
        uses: actions/download-artifact@v8
        with:
          name: aarch64 build (${{ inputs.DEVICE }})

      - name: Extract artifact aarch64 build
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            tar -xf build.build.aarch64.tar
          max_attempts: 3
          retry_interval: 10

      - name: Clean up compressed aarch64 build file
        run: rm build.build.aarch64.tar

      - name: Download qt6 (${{ inputs.DEVICE }})
        if: ${{ inputs.DEVICE == 'SM8250' || inputs.DEVICE == 'SM8550' || inputs.DEVICE == 'SM8650' || inputs.DEVICE == 'SM8750' }}
        uses: actions/download-artifact@v8
        with:
          name: qt6 (${{ inputs.DEVICE }})

      - name: Extract artifact qt6
        if: ${{ inputs.DEVICE == 'SM8250' || inputs.DEVICE == 'SM8550' || inputs.DEVICE == 'SM8650' || inputs.DEVICE == 'SM8750' }}
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            sudo tar --zstd -xf build.qt6.tar.zst --same-owner
          max_attempts: 3
          retry_interval: 10

      - name: Clean up compressed qt6 file
        if: ${{ inputs.DEVICE == 'SM8250' || inputs.DEVICE == 'SM8550' || inputs.DEVICE == 'SM8650' || inputs.DEVICE == 'SM8750' }}
        run: rm build.qt6.tar.zst

      - name: Build eden-sa
        uses: corrupt952/actions-retry-command@v1.0.7
        with:
          command: |
            ./scripts/get_env > .env
            set -e
            { docker run --init --env-file .env --rm --user $(id -u):$(id -g) -v ${PWD}:${PWD} -w ${PWD} "ghcr.io/${{ inputs.OWNER_LC }}/rocknix-build:latest" \
              bash -c "./scripts/build_mt eden-sa"; echo $? > docker_exit_code; } | tee output.log | grep -E  --color=never --line-buffered "^GET|^UNPACK|^BUILD|^INSTALL" || true
            exit_code=$(<docker_exit_code)
            exit $exit_code
          max_attempts: 6
          retry_interval: 10

      - name: Archive output.logs (${{ inputs.DEVICE }}-aarch64-eden-sa)
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: output.logs (${{ inputs.DEVICE }}-aarch64-eden-sa)
          path: |
            output.log
            ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.threads/logs/

      - name: Clean ccache
        run: |
          export CCACHE_DIR=./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.ccache
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -s -v
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -M 2G
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -c
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -s -v
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/toolchain/bin/ccache -z

      - name: Tar ccache
        run: |
          tar -cf ccache-aarch64-${{ inputs.DEVICE }}-eden-sa.tar ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.ccache 

      - name: Save ccache
        uses: ncipollo/release-action@v1
        with:
          tag: ccache
          artifacts: ccache-aarch64-${{ inputs.DEVICE }}-eden-sa.tar
          allowUpdates: true
          makeLatest: true
          prerelease: true
          body: ccache
          token: ${{ secrets.GH_PAT }}
          repo: ${{ vars.CACHE_REPO || 'distribution-cache' }}
        continue-on-error: true

      - name: Compress directory
        run: |
          tar --zstd -cf build.eden-sa.tar.zst \
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/install_pkg/eden-sa-* \
          ./build.ROCKNIX-${{ inputs.DEVICE }}.aarch64/.stamps/eden-sa

      - uses: actions/upload-artifact@v7
        with:
          name: eden-sa (${{ inputs.DEVICE }})
          path: build.eden-sa.tar.zst
          compression-level: 0
          if-no-files-found: error
