name: Fail on upstream packages changes

on:
  pull_request:
    paths:
      - 'packages/**'

jobs:
  check-upstream-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if upstream packages changed
        run: |
          echo "🚫 ERROR: Modifying files in the upstream 'packages' folder is forbidden!"
          echo "Please do not make changes to this folder."
          exit 1